---
name: busybox 1.34-musl, musl 

on:
  pull_request:
  push:
    paths:
      - '1.34/**'
      - '.github/workflows/1.34.1-musl.yml'
  schedule:
    - cron: '40 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test Busybox 1.34.1-musl
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 1.34.1-musl && docker build -t busybox-1.34.1-musl .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro busybox-1.34.1-musl

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 1.34.1-musl/
          file: 1.34.1-musl/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:1.34.1-musl, ${{ github.repository }}:1.34-musl, ${{ github.repository }}:musl, ${{ github.repository }}:stable-musl
